### ISSUE TITLE
Possible Redundant If condition in insertApporipriately

### ISSUE THREAD

**Issue by abhishekvispute** [razor-network/contracts#414] opened 2021-09-09 08:57 UTC
In insertAppropriately 
We have one condition 
https://github.com/razor-network/contracts/blob/ef7dd744ece41079257d4591ec7cfc46a24b41ca/contracts/Core/BlockManager.sol#L238

but I am not able to think of any reason, of it becoming true 
because 
```proposedBlocks[epoch][i].biggestInfluence ``` we set in propose
```
   proposedBlocks[epoch][numProposedBlocks] = Structs.Block(proposerId, medians, iteration, biggestInfluence);
   _insertAppropriately(epoch, numProposedBlocks, iteration, biggestInfluence);
```
And same is passed in _insertAppropriately, so I think it always will be equal only

**Comment by GauravJain9** [comment] 2021-09-09 08:59
This I have removed in my PR. 
I have tested this and this check is never true

**Comment by hrishikeshio** [comment] 2021-09-13 09:17
https://github.com/razor-network/contracts/blob/ef7dd744ece41079257d4591ec7cfc46a24b41ca/contracts/Core/BlockManager.sol#L238

Should be `if (proposedBlocks[epoch][sortedProposedBlockIds[epoch][i]].biggestInfluence < biggestInfluence) {`

@abhishekvispute

**Comment by abhishekvispute** [comment] 2021-09-13 14:41
Hi Guys, @razor-network/engineering 
Had discussion over this 
This if condition over biggest influence is not redundant 

Staker can pass anyone as biggestInfluncerId in propose 
and we are not verifying it 
so the staker with more correct biggestInfluence passed in propose should be given pref.

**Comment by SkandaBhat** [comment] 2021-09-14 12:55
Closing this as it is a duplicate of #428 .

**Closed by SkandaBhat** 2021-09-14 12:55 UTC
Labels: Analysis
