### ISSUE TITLE
Propose

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/contracts#442] opened 2021-09-16 07:24 UTC
https://dashboard.tenderly.co/razor/razor-network/tx/mumbai/0x0a4301dd6b3f43efbe7334cf18c7b7ba7148a5bf20974c054441617c0a748377

**Comment by abhishekvispute** [comment] 2021-09-21 05:27
picking this up

**Comment by abhishekvispute** [comment] 2021-09-21 06:54
Hi Guys @razor-network/engineering ,

I created the fork from given transaction block, 
and executed the transaction with original gas limit and little higher gas limit.
for higher gas limit it passed, so we can rule out any revert on contract.
Its legitimate out of gas issue

https://dashboard.tenderly.co/razor/razor-network/fork/0b2f75c2-8a84-4587-8055-5f5f50846b14
<img width="1150" alt="Screenshot 2021-09-21 at 12 22 05 PM" src="https://user-images.githubusercontent.com/46760063/134124913-e8826fe9-62f7-4c1e-8c13-99781b5f31ec.png">

@ashish10677 how gas limit is decided on cli ?

**Comment by abhishekvispute** [comment] 2021-09-21 07:16
<img width="947" alt="Screenshot 2021-09-21 at 12 45 36 PM" src="https://user-images.githubusercontent.com/46760063/134127849-83a02cca-8ef2-4182-93a6-add3ead77638.png">

**Comment by hrishikeshio** [comment] 2021-09-21 07:53
@Yashk767

**Comment by ashish10677** [comment] 2021-09-22 13:01
> Hi Guys @razor-network/engineering ,
> 
> I created the fork from given transaction block,
> and executed the transaction with original gas limit and little higher gas limit.
> for higher gas limit it passed, so we can rule out any revert on contract.
> Its legitimate out of gas issue
> 
> https://dashboard.tenderly.co/razor/razor-network/fork/0b2f75c2-8a84-4587-8055-5f5f50846b14
> <img alt="Screenshot 2021-09-21 at 12 22 05 PM" width="1150" src="https://user-images.githubusercontent.com/46760063/134124913-e8826fe9-62f7-4c1e-8c13-99781b5f31ec.png">
> 
> @ashish10677 how gas limit is decided on cli ?

Gas limit is calculated by `geth`'s method `estimateGas`. Opening an issue on razor-go to increase the gas limit by 15%.

**Comment by hrishikeshio** [comment] 2021-09-26 17:47
Error still happening after providing extra gas.
https://dashboard.tenderly.co/razor/razor-network/tx/mumbai/0xb818c9e742ef92190d5cd502626145ba4bf7f30e6c93c0f54c897c1e743c32b9/debugger

Following can be the cause:

Staker A proposes with iteration 1000
Staker B proposes with iteration 500
in insertApropriately, pushAt=0 since
```            if (proposedBlocks[epoch][i].iteration > _block.iteration) {
```
in following line j=0 and j-1 will cause underflow 
```            proposedBlocks[epoch][j] = proposedBlocks[epoch][j - 1];
```

**Comment by abhishekvispute** [comment] 2021-09-27 08:59
hmm this transaction also passed with gaslimit 8000000

**Comment by abhishekvispute** [comment] 2021-09-27 09:05
> Error still happening after providing extra gas.
> https://dashboard.tenderly.co/razor/razor-network/tx/mumbai/0xb818c9e742ef92190d5cd502626145ba4bf7f30e6c93c0f54c897c1e743c32b9/debugger
> 

At least 7,93,260 gas is needed for this tx to pass, where only 7,36,451 was passed on live net

**Comment by ashish10677** [comment] 2021-09-27 09:06
@hrishikeshio @SkandaBhat is the `v0.1.54` version deployed while testing this txn?

**Comment by abhishekvispute** [comment] 2021-09-27 09:11
> Following may be the cause:
> 
> Staker A proposes with iteration 1000
> Staker B proposes with iteration 500
> in insertApropriately, pushAt==0 since
> 
> ```
> if (proposedBlocks[epoch][i].iteration > _block.iteration) {
> ```
> 
> in following lin j-1 will cause underflow since j=0
> 
> ```
> proposedBlocks[epoch][j] = proposedBlocks[epoch][j - 1];
> ```

Hmm here 
the state would be 
1000
first
then push 500
1000, 500

then for loop from j=1 , j>0, j--
block[j] = block[j-1]

which would result 1000, 1000
then 
assign blockId at pushat
so 
500, 1000

hence mostly this shouldn't revert

**Comment by SkandaBhat** [comment] 2021-09-27 09:24
> @hrishikeshio @SkandaBhat is the razor-go `v0.1.54` version deployed while testing this txn?

No. cc @hrishikeshio this did not have the patch built in.

**Comment by abhishekvispute** [comment] 2021-10-01 13:03
Closing this as its cli issue

**Closed by abhishekvispute** 2021-10-01 13:03 UTC
Labels: bug
